services:
  app:
    build:
      context: .
    container_name: short
    ports:
      - '7654:7654'
    environment:
      - BASIC_AUTH_USERNAME=admin
      - BASIC_AUTH_PASSWORD=test123
    volumes:
      - .:/usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 7654
